package io.ts7.carplay;

/** Fixed codes only: never accept peer names, addresses or exception messages. */
public enum EventCode {
    APP_OPEN, BT_CONNECT, BT_DISCONNECT, WIFI_CONNECT, NETWORK_LOSS,
    AUTHENTICATION_BLOCKED, CARPLAY_SESSION_START, SESSION_LOST,
    VIDEO_SPS_RECEIVED, VIDEO_PPS_RECEIVED, DECODER_CONFIGURED, FIRST_FRAME,
    DECODER_ERROR, CODEC_CALL_TIMEOUT, VIDEO_STALL, RECOVERY_START, RECOVERY_SUCCESS, RECOVERY_EXHAUSTED,
    KEYFRAME_REQUEST, TEST_START, TEST_STOP, STREAM_RESET, QUEUE_RESYNC,
    INPUT_REJECTED, SURFACE_LOST, AUDIO_STARTED, AUDIO_STOPPED, AUDIO_ERROR,
    STATE_IDLE, STATE_BT_DISCOVERY, STATE_BT_CONNECTED, STATE_WIFI_CONNECTING,
    STATE_WIFI_CONNECTED, STATE_CARPLAY_NEGOTIATING, STATE_STREAMING,
    STATE_RECOVERING, STATE_ERROR
}
